name: Testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  gofmt:
    name: go fmt (Go ${{ matrix.go }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ["1.23", "1.22"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run go fmt
        if: runner.os != 'Windows'
        run: diff -u <(echo -n) <(gofmt -d -s .)

  govet:
    name: go vet (Go ${{ matrix.go }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ["1.23", "1.22"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run go vet
        run: make vet

  staticcheck:
    name: staticcheck (Go ${{ matrix.go }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ["1.23", "1.22"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2024.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}

  unittesting:
    name: unit testing (Go ${{ matrix.go }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ["1.23", "1.22"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run Unit tests.
        run: make test
